# CORE
# NRL 5520
# CORE service to setup PCapper monitoring at scenario start

import os
import sys
import json
import logging

from core.service import CoreService
from core.service import ServiceMode

class CaaS(CoreService):
    # a unique name is required, without spaces
    name = "PCapper-Dst"
    # you can create your own group here
    group = "ProtoSvc"
    # Any services that want to steal IP addresses from interfaces need a
    # dependency UPON this service, so that they don't get the address before we
    # can read it.
    # list of other services this service depends on
    dependencies = ()
    # validation check [Note: will detect PCapper instances from other services]
    validate = ('pgrep -x pcapper',)
    meta = "monitors network traffic and logs/reports to collector(s)"
    # validation time (defaults to 0.125 seconds) [N/A]
    # per-node directories [N/A]
    dirs = ("")
    # generated files (without a full path, this file goes in the node's dir,
    # e.g. /tmp/pycore.12345/n1.conf/)
    configs = (name + '.sh', )
    # list of startup commands, also may be generated during startup
    startup = ('sh ' + configs[0],)
    # list of shutdown commands
    # Note: This will clobber all PCapper services, including those started by
    # another service.
    shutdown = ('pkill -x pcapper')

    @classmethod
    def generate_config(cls, node, filename):
        """
        Run PCapper agent only on routing nodes
        """
        cfg = "#!/bin/sh\n# auto-generated by PCapper-Dst CORE service\n\n"
        comments = ""
        cmd = ""
        if 'E2' in node.name:
            # This system is administratively supposed to have 2 interfaces
            cmd += "/usr/local/bin/pcapper -m dst -i eth1 -s ctrl0 -p 7076 -f pcapper-dst.eth1.log &\n"
        else:
            pass
        # All systems are administratively declared to have an eth0 interface
        cmd += "/usr/local/bin/pcapper -m dst -i eth0 -s ctrl0 -p 7075 -f pcapper-dst.eth0.log &\n"
        return cmd
